name: Descargar M3U

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      M3U_LINK: ${{ secrets.URL_FILE_LINK }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install requests

      - name: Descargar archivo M3U usando el secreto
        run: python extraer_m3u_Shu_Version2.py
        env:
          M3U_LINK: ${{ secrets.URL_FILE_LINK }}

      - name: Hacer commit de lista_varios.m3u
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add lista_varios.m3u
          git commit -m "Actualizar lista_varios.m3u" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/TarunG78/livetv.git HEAD:main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          
